### ISSUE TITLE
Feature Request: Add Height and Width Attributes to <monotone-shape>

### ISSUE THREAD

**Issue by yashrajbharti** [yashrajbharti/Monotone-Shapes#1]
**Description:**

I’d like to propose adding two new attributes, `height` and `width`, to the `<monotone-shape>` component. Since the shapes are SVGs, it would be beneficial to allow users to customize the size of the icons directly through these attributes.

**Proposed Changes:**

1. **Add `height` attribute**:
   - This attribute will define the height of the SVG shape.
   - Example usage: 
     ```html
     <monotone-shape shape-id="1" height="50" text=""></monotone-shape>
     ```

2. **Add `width` attribute**:
   - This attribute will define the width of the SVG shape.
   - Example usage: 
     ```html
     <monotone-shape shape-id="1" width="50" text=""></monotone-shape>
     ```

3. **Usage of both attributes together**:
   - Example of using both `height` and `width`:
     ```html
     <monotone-shape shape-id="1" height="50" width="100" text="Example"></monotone-shape>
     ```

**Benefits:**

- Greater flexibility for developers to adapt icons to their specific design needs.
- Consistent experience when working with SVGs, making it easier to maintain design integrity across different screen sizes.

**Additional Notes:**

- Please ensure that the default behavior remains intact if the attributes are not provided.
- Consider updating the documentation to include examples of how to use the new attributes.

**Comment by rovertrack** [comment]
while using montone shape component the shape and text attribute 
you want to add the width and height for the component for users to adjust height and width of component


assign it to me ... if this is what you meant

**Comment by rovertrack** [comment]
???

**Comment by yashrajbharti** [comment]
feel free to go ahead

**Comment by rovertrack** [comment]
assign me ,...

**Comment by yashrajbharti** [comment]
Thank you for your interest in contributing! While anyone is welcome to submit a pull request (PR), I typically assign issues to contributors based on their previous work and the quality of their submissions. If you decide to create a PR for the task, I'll be happy to review it. If it aligns with our needs and meets our standards, I'll consider assigning you the issue.

Looking forward to seeing your contributions!
