### ISSUE TITLE
Landing page UI 

### ISSUE THREAD

**Issue by rohitmore07** [yashrajbharti/Monotone-Shapes#3]
To improve the website's UI, let's add smooth hover animations for interactive elements, refine spacing for a cleaner look and apply a cohesive color scheme. These updates will make the site more visually appealing and user-friendly.

**Comment by yashrajbharti** [comment]
I like the idea, but at the same time the issue lacks proper description of what to do with the landing page. "Make it Better" has a different meaning to different people. In what ways would you want it to be more visually appealing. 
If you can incorporate some design files (using Figma or Sketch) with your idea, I am definitely interested in making the changes.

**Comment by rohitmore07** [comment]
![Monotone](https://github.com/user-attachments/assets/d5a143cc-76ee-42fa-9442-cfa829418716)

**Comment by rohitmore07** [comment]
@yashrajbharti It would be great if you could check designed image and provide any feedback or suggestions.

**Comment by yashrajbharti** [comment]
I would love to keep it grayscale and monotone. I am not sure about the help page as well. The avatar is definitely out of theme as well

**Comment by rohitmore07** [comment]
![Monotone](https://github.com/user-attachments/assets/9be095f3-bd05-4f4f-9892-0ac5bd29c69a)
Check Once!

**Comment by yashrajbharti** [comment]
Much better, any better ways to design the input text field, as it may have longer text values as well

**Comment by rohitmore07** [comment]
![Monotone](https://github.com/user-attachments/assets/b9e4a852-be2c-4142-9c00-9c9b4d86f4e8)

**Comment by yashrajbharti** [comment]
Now it's better.
But if we think about usage, the input for this textfield has to reflect by creating a resultant svg directly below it, so it's accessible and exists within that form.
So the multiple shapes directly under the textfield need to be placed somewhere else.
also I hope the background can be created by a repeating pattern either through svg or css and `background-repeat: repeat`

**Comment by rohitmore07** [comment]
Thank you for the input. I’ll start implementing these changes!

**Comment by yashrajbharti** [comment]
I have added your changes and closed the issue. I haven't added the background as it must be generated using CSS patterns rather than two images. Feel free to open another issue. Check this resource for more: https://10015.io/tools/css-background-pattern-generator

**Comment by rohitmore07** [comment]
Perfect! The grid background will look great with random squares fill.
